<%@ Page Language="VB" AutoEventWireup="false" CodeFile="MainPage.aspx.vb" Inherits="MainPage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 438px;
        }
        .auto-style2 {
            width: 438px;
            height: 26px;
        }
        .auto-style3 {
            height: 26px;
            width: 95px;
        }
        .auto-style4 {
            width: 343px;
        }
        .auto-style5 {
            height: 26px;
            width: 343px;
        }
        .auto-style6 {
            width: 95px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <br />
        <br />
        <table style="width:100%;">
            <tr>
                <td class="auto-style1">
                    <asp:GridView ID="gvStudent" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField HeaderText="ID" Visible="False" />
                            <asp:BoundField DataField="SID" HeaderText="StudentID">
                            <ItemStyle Width="40px" />
                            </asp:BoundField>
                            <asp:BoundField DataField="Sname" HeaderText="Student Name">
                            <ItemStyle Width="40px" />
                            </asp:BoundField>
                            <asp:TemplateField HeaderText="Student Major">
                                <EditItemTemplate>
                                    <asp:DropDownList ID="ddlmajors" runat="server">
                                    </asp:DropDownList>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="Label1" runat="server" Text='<%# Bind("SMajor") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EditRowStyle BackColor="#7C6F57" />
                        <EmptyDataTemplate>
                            <asp:DropDownList ID="DropDownList1" runat="server">
                            </asp:DropDownList>
                        </EmptyDataTemplate>
                        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#E3EAEB" />
                        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F8FAFA" />
                        <SortedAscendingHeaderStyle BackColor="#246B61" />
                        <SortedDescendingCellStyle BackColor="#D4DFE1" />
                        <SortedDescendingHeaderStyle BackColor="#15524A" />
                    </asp:GridView>
                </td>
                <td class="auto-style4">
                    <asp:GridView ID="gvProf" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:BoundField HeaderText="ID" Visible="False" />
                            <asp:BoundField DataField="PName" HeaderText="Professor Name">
                            <ItemStyle Width="150px" />
                            </asp:BoundField>
                            <asp:BoundField DataField="POffice" HeaderText="Office Location">
                            <ItemStyle Width="40px" />
                            </asp:BoundField>
                            <asp:BoundField DataField="PPhone" HeaderText="Phone Number">
                            <ItemStyle Width="100px" />
                            </asp:BoundField>
                            <asp:BoundField DataField="PCourse" HeaderText="Course" />
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                </td>
                <td class="auto-style6">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style1">&nbsp;</td>
                <td class="auto-style4">&nbsp;</td>
                <td class="auto-style6">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style1">&nbsp;&nbsp;&nbsp;&nbsp; Student ID:&nbsp;&nbsp;<asp:TextBox ID="txtStudentID" runat="server" style="margin-left: 6px" Width="170px"></asp:TextBox>
                </td>
                <td class="auto-style4">Professor Name:&nbsp;&nbsp; <asp:TextBox ID="txtProfName" runat="server" style="margin-left: 3px" Width="170px"></asp:TextBox>
                &nbsp;Course: <asp:TextBox ID="txtCourse" runat="server" style="margin-left: 3px" Width="170px"></asp:TextBox>
                </td>
                <td class="auto-style6">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style1">Student Name:&nbsp; &nbsp;<asp:TextBox ID="txtStudentName" runat="server" Width="170px"></asp:TextBox>
                </td>
                <td class="auto-style4">Office Location:&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="txtLocation" runat="server" Width="170px"></asp:TextBox>
                </td>
                <td class="auto-style6">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Major:&nbsp;
                    <asp:DropDownList ID="lstMajor" runat="server" Height="16px" style="margin-left: 0px" Width="170px">
                        <asp:ListItem Value="CST">Computer Science</asp:ListItem>
                        <asp:ListItem Value="ENG">English</asp:ListItem>
                        <asp:ListItem Value="MAT">Math</asp:ListItem>
                    </asp:DropDownList>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnAddStudent" runat="server" Text="Add Student" />
                </td>
                <td class="auto-style5">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Phone:&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="txtPhone" runat="server" style="margin-left: 2px" Width="170px"></asp:TextBox>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnAddProf" runat="server" Text="Add Prof" />
                </td>
                <td class="auto-style3"></td>
            </tr>
            <tr>
                <td class="auto-style2"></td>
                <td class="auto-style5"></td>
                <td class="auto-style3"></td>
            </tr>
            <tr>
                <td class="auto-style2">
                    <asp:GridView ID="gvCourse" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                        <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                        <Columns>
                            <asp:BoundField HeaderText="ID" Visible="False" />
                            <asp:BoundField DataField="CNumber" HeaderText="Course">
                            <ItemStyle Width="75px" />
                            </asp:BoundField>
                            <asp:BoundField DataField="CStudent" HeaderText="Student">
                            <ItemStyle Width="40px" />
                            </asp:BoundField>
                            <asp:BoundField DataField="CProfessor" HeaderText="Professor">
                            <ItemStyle Width="100px" />
                            </asp:BoundField>
                            <asp:BoundField DataField="CGrade" HeaderText="Grade">
                            <ItemStyle Width="20px" />
                            </asp:BoundField>
                        </Columns>
                        <EditRowStyle BackColor="#999999" />
                        <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                        <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#E9E7E2" />
                        <SortedAscendingHeaderStyle BackColor="#506C8C" />
                        <SortedDescendingCellStyle BackColor="#FFFDF8" />
                        <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                    </asp:GridView>
                </td>
                <td class="auto-style5">Search By:&nbsp;&nbsp;
                    <asp:DropDownList ID="lstSrchby" runat="server" AutoPostBack="True">
                        <asp:ListItem Value="CStudent">Student</asp:ListItem>
                        <asp:ListItem Value="CProfessor">Professor</asp:ListItem>
                        <asp:ListItem Value="CNumber">Course</asp:ListItem>
                    </asp:DropDownList>
                    <br />
                    <br />
                    Values:&nbsp;&nbsp;
                    <asp:DropDownList ID="lstSrchValues" runat="server">
                    </asp:DropDownList>
                    <br />
                    <br />
                    <asp:Button ID="gpaButton" runat="server" Text="Calculate" />
                </td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">GPA:&nbsp;&nbsp;&nbsp;&nbsp;
                    <asp:TextBox ID="txtGPA" runat="server" Enabled="False"></asp:TextBox>
                </td>
                <td class="auto-style5"></td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style5">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">Student:&nbsp;&nbsp;&nbsp;&nbsp; <asp:DropDownList ID="lstStudentSel" runat="server">
                    </asp:DropDownList>
                </td>
                <td class="auto-style5">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">Professor:&nbsp;
                    <asp:DropDownList ID="lstProfSel" runat="server">
                    </asp:DropDownList>
                </td>
                <td class="auto-style5">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style2">Grade:&nbsp;&nbsp;
                    <asp:TextBox ID="txtGrade" runat="server"></asp:TextBox>
&nbsp;&nbsp;&nbsp;
                    <asp:Button ID="btnAddCourse" runat="server" Text="Add Course" />
                </td>
                <td class="auto-style5">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
        </table>
        <br />
    
    </div>
    </form>
</body>
</html>
